github: [metadata]
theme: jekyll-theme-cayman

content_categories: ["Requirements", "Justifications", "Standup Minutes", "Sprint Retrospectives", "Wiki", "Javascript", "Vendors"]

defaults:
  - scope:
      path: "content"
    values:
      content: true
      layout: document