github: [metadata]
theme: jekyll-theme-cayman

content_categories: ["Requirements", "Justifications", "Standup Minutes", "Sprint Retrospectives", "Wiki", "Javascript", "Vendors", "Diagrams"]
content_subcategories:
  Javascript: ["Database", "Models", "Routes", "Controllers", "Libraries", "Front-End"]

defaults:
  - scope:
      path: "content"
    values:
      content: true
      layout: document